from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
import textwrap
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
GENERATOR = REPO_ROOT / "scripts" / "generate_docs.py"
DESCRIPTIONS = REPO_ROOT / "docs" / "cli-descriptions.yaml"
REFERENCE = REPO_ROOT / "docs" / "cli-reference.md"

EXPECTED_NESTED_PATHS = {
    "jfox model download",
    "jfox auto-summary forget",
    "jfox auto-summary prune",
    "jfox backup restore",
    "jfox fragments list",
    "jfox candidates promote",
    "jfox candidates reject",
    "jfox gem-synth status",
    "jfox gem-synth dedup-backfill",
    "jfox bookshelf add",
    "jfox bookshelf remove",
    "jfox moc create",
    "jfox moc update",
    "jfox moc diagnose",
}


def _isolated_env(tmp_path: Path) -> dict[str, str]:
    test_home = tmp_path / "home"
    test_home.mkdir(parents=True)
    env = os.environ.copy()
    env.update(
        {
            "HOME": str(test_home),
            "USERPROFILE": str(test_home),
            "ZK_CONFIG_PATH": str(test_home / "zk_config.json"),
            "ZK_KB_ROOT": str(test_home / ".zettelkasten"),
            "PYTHONUTF8": "1",
        }
    )
    return env


def _run_generator(output: Path, tmp_path: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [
            sys.executable,
            str(GENERATOR),
            "--output",
            str(output),
            "--descriptions",
            str(DESCRIPTIONS),
            "--inventory-output",
            str(tmp_path / "plugin-inventory.md"),
        ],
        cwd=REPO_ROOT,
        env=_isolated_env(tmp_path),
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=False,
    )


def _run_real_app_probe(script: str, tmp_path: Path) -> subprocess.CompletedProcess[str]:
    """Import the real app in a fresh, fully isolated interpreter."""
    return subprocess.run(
        [sys.executable, "-c", textwrap.dedent(script)],
        cwd=REPO_ROOT,
        env=_isolated_env(tmp_path),
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=False,
    )


def test_real_jfox_command_tree_coverage(tmp_path: Path):
    """The live Typer app exposes every current command path in the reference catalog."""
    result = _run_real_app_probe(
        """
        import json
        from typer.main import get_command
        from jfox.cli import app
        from scripts.generate_docs import extract_commands, load_descriptions, validate_descriptions

        commands = extract_commands(get_command(app))
        paths = {command.path for command in commands}
        descriptions = load_descriptions(__import__("pathlib").Path("docs/cli-descriptions.yaml"))
        validate_descriptions(paths, descriptions)
        print(json.dumps({"paths": sorted(paths), "count": len(commands)}))
        """,
        tmp_path,
    )

    assert result.returncode == 0, result.stderr
    payload = json.loads(result.stdout)
    paths = set(payload["paths"])
    assert EXPECTED_NESTED_PATHS <= paths
    assert "jfox" in paths
    assert payload["count"] == len(paths)


def test_real_jfox_command_tree_does_not_invoke_callbacks(tmp_path: Path):
    """Introspection of the real app does not execute a command callback."""
    result = _run_real_app_probe(
        """
        from typer.main import get_command
        from jfox.cli import app
        from scripts.generate_docs import extract_commands

        root = get_command(app)

        def fail_if_called(*args, **kwargs):
            raise AssertionError("command callback was invoked during introspection")

        def guard_callbacks(command):
            if getattr(command, "callback", None) is not None:
                command.callback = fail_if_called
            for child in getattr(command, "commands", {}).values():
                guard_callbacks(child)

        guard_callbacks(root)
        commands = extract_commands(root)
        assert commands
        assert all(command.path.startswith("jfox") for command in commands)
        print("callbacks not invoked")
        """,
        tmp_path,
    )

    assert result.returncode == 0, result.stderr
    assert result.stdout.strip() == "callbacks not invoked"


def test_generator_subprocess_writes_english_reference_without_runtime_dependencies(tmp_path: Path):
    output = tmp_path / "nested" / "cli-reference.md"

    result = _run_generator(output, tmp_path)

    assert result.returncode == 0, result.stderr
    assert output.is_file()
    content = output.read_text(encoding="utf-8")
    assert "This file is generated by scripts/generate_docs.py." in content
    assert "# JFox CLI Reference" in content
    assert "## `jfox auto-summary forget`" in content
    assert "## `jfox backup restore`" in content
    assert "## `jfox bookshelf add`" in content
    assert "## `jfox moc diagnose`" in content
    assert "Search notes by keyword, semantic meaning, or both." in content
    assert not any("\u4e00" <= char <= "\u9fff" for char in content)
    assert "\x1b[" not in content
    assert "/home/" not in content


def test_generator_is_deterministic(tmp_path: Path):
    first = tmp_path / "first" / "cli-reference.md"
    second = tmp_path / "second" / "cli-reference.md"

    first_result = _run_generator(first, tmp_path / "first-home")
    second_result = _run_generator(second, tmp_path / "second-home")

    assert first_result.returncode == 0, first_result.stderr
    assert second_result.returncode == 0, second_result.stderr
    assert first.read_bytes() == second.read_bytes()
    assert (
        hashlib.sha256(first.read_bytes()).hexdigest()
        == hashlib.sha256(second.read_bytes()).hexdigest()
    )


def test_generator_config_safety(tmp_path: Path):
    real_config = Path.home() / ".zk_config.json"
    before_bytes = real_config.read_bytes() if real_config.exists() else None
    before_hash = hashlib.sha256(before_bytes).hexdigest() if before_bytes is not None else None
    before_data = json.loads(before_bytes) if before_bytes is not None else None
    output = tmp_path / "cli-reference.md"

    result = _run_generator(output, tmp_path)

    assert result.returncode == 0, result.stderr
    after_bytes = real_config.read_bytes() if real_config.exists() else None
    after_hash = hashlib.sha256(after_bytes).hexdigest() if after_bytes is not None else None
    after_data = json.loads(after_bytes) if after_bytes is not None else None
    assert after_hash == before_hash
    assert after_data == before_data
    assert not (REPO_ROOT / "zk_config.json").exists()
    assert not (REPO_ROOT / "config.json").exists()


def test_readme_boundary_links_generated_reference_without_exhaustive_sections():
    """README links to the generated reference without duplicating its command sections."""
    readme = (REPO_ROOT / "README.md").read_text(encoding="utf-8")
    reference = REFERENCE.read_text(encoding="utf-8")

    assert "[CLI Reference](docs/cli-reference.md)" in readme
    assert "This file is generated by scripts/generate_docs.py." in reference
    assert "## `jfox auto-summary forget`" in reference
    assert "## `jfox auto-summary forget`" not in readme
    assert "## `jfox bookshelf add`" not in readme
    assert "exhaustive generated CLI reference is planned" not in readme.lower()


@pytest.mark.parametrize(
    "command_path",
    sorted(EXPECTED_NESTED_PATHS),
)
def test_reference_contains_each_required_nested_command(command_path: str):
    content = REFERENCE.read_text(encoding="utf-8")

    assert f"## `{command_path}`" in content


def test_generator_rejects_partial_environment_without_using_real_paths(monkeypatch, tmp_path):
    """A supplied config path must not allow the real KB root during app import."""
    from scripts.generate_docs import _ensure_isolated_config_environment

    monkeypatch.setenv("ZK_CONFIG_PATH", str(tmp_path / "config.json"))
    monkeypatch.delenv("ZK_KB_ROOT", raising=False)

    _ensure_isolated_config_environment()

    assert os.environ["ZK_CONFIG_PATH"] == str(tmp_path / "config.json")
    assert os.environ["ZK_KB_ROOT"] != str(Path.home() / ".zettelkasten")
    assert Path(os.environ["ZK_KB_ROOT"]).parent != Path.home()


def test_generator_rejects_missing_config_path_without_using_real_config(monkeypatch, tmp_path):
    """A supplied KB root must not allow the real global config during app import."""
    from scripts.generate_docs import _ensure_isolated_config_environment

    monkeypatch.delenv("ZK_CONFIG_PATH", raising=False)
    monkeypatch.setenv("ZK_KB_ROOT", str(tmp_path / "zettelkasten"))

    _ensure_isolated_config_environment()

    assert Path(os.environ["ZK_CONFIG_PATH"]).parent != Path.home()
    assert os.environ["ZK_KB_ROOT"] == str(tmp_path / "zettelkasten")


def test_generator_reports_catalog_remediation(tmp_path):
    output = tmp_path / "reference.md"
    missing_catalog = tmp_path / "missing.yaml"

    result = subprocess.run(
        [
            sys.executable,
            str(GENERATOR),
            "--output",
            str(output),
            "--descriptions",
            str(missing_catalog),
        ],
        cwd=REPO_ROOT,
        env=_isolated_env(tmp_path / "catalog-home"),
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=False,
    )

    assert result.returncode != 0
    assert "update docs/cli-descriptions.yaml" in result.stderr
    assert "rerun" in result.stderr.lower()


def test_generator_reports_output_remediation(tmp_path):
    output = tmp_path / "not-a-directory" / "reference.md"
    output.parent.write_text("occupied", encoding="utf-8")

    result = subprocess.run(
        [
            sys.executable,
            str(GENERATOR),
            "--output",
            str(output),
            "--descriptions",
            str(DESCRIPTIONS),
        ],
        cwd=REPO_ROOT,
        env=_isolated_env(tmp_path / "output-home"),
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=False,
    )

    assert result.returncode != 0
    assert "output" in result.stderr.lower()
    assert "permission" in result.stderr.lower() or "path" in result.stderr.lower()
    assert "rerun" in result.stderr.lower()
