from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path

import pytest
from typer.main import get_command

from jfox.cli import app
from scripts.generate_docs import extract_commands, load_descriptions, validate_descriptions

REPO_ROOT = Path(__file__).resolve().parents[2]
GENERATOR = REPO_ROOT / "scripts" / "generate_docs.py"
DESCRIPTIONS = REPO_ROOT / "docs" / "cli-descriptions.yaml"
REFERENCE = REPO_ROOT / "docs" / "cli-reference.md"

EXPECTED_NESTED_PATHS = {
    "jfox model download",
    "jfox auto-summary forget",
    "jfox auto-summary prune",
    "jfox backup restore",
    "jfox fragments list",
    "jfox candidates promote",
    "jfox candidates reject",
    "jfox gem-synth status",
    "jfox gem-synth dedup-backfill",
    "jfox bookshelf add",
    "jfox bookshelf remove",
    "jfox moc create",
    "jfox moc update",
    "jfox moc diagnose",
}


def _isolated_env(tmp_path: Path) -> dict[str, str]:
    test_home = tmp_path / "home"
    test_home.mkdir(parents=True)
    env = os.environ.copy()
    env.update(
        {
            "HOME": str(test_home),
            "USERPROFILE": str(test_home),
            "ZK_CONFIG_PATH": str(test_home / "zk_config.json"),
            "ZK_KB_ROOT": str(test_home / ".zettelkasten"),
            "PYTHONUTF8": "1",
        }
    )
    return env


def _run_generator(output: Path, tmp_path: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [
            sys.executable,
            str(GENERATOR),
            "--output",
            str(output),
            "--descriptions",
            str(DESCRIPTIONS),
        ],
        cwd=REPO_ROOT,
        env=_isolated_env(tmp_path),
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=False,
    )


def test_real_jfox_command_tree_coverage():
    """The live Typer app exposes every current command path in the reference catalog."""
    commands = extract_commands(get_command(app))
    paths = {command.path for command in commands}

    assert EXPECTED_NESTED_PATHS <= paths
    assert "jfox" in paths
    assert len(paths) == len(commands)

    descriptions = load_descriptions(DESCRIPTIONS)
    validate_descriptions(paths, descriptions)


def test_real_jfox_command_tree_does_not_invoke_callbacks():
    """Introspection of the real app does not execute a command callback."""
    commands = extract_commands(get_command(app))

    assert commands
    assert all(command.path.startswith("jfox") for command in commands)


def test_generator_subprocess_writes_english_reference_without_runtime_dependencies(tmp_path: Path):
    output = tmp_path / "nested" / "cli-reference.md"

    result = _run_generator(output, tmp_path)

    assert result.returncode == 0, result.stderr
    assert output.is_file()
    content = output.read_text(encoding="utf-8")
    assert "This file is generated by scripts/generate_docs.py." in content
    assert "# JFox CLI Reference" in content
    assert "## `jfox auto-summary forget`" in content
    assert "## `jfox backup restore`" in content
    assert "## `jfox bookshelf add`" in content
    assert "## `jfox moc diagnose`" in content
    assert "Search notes by keyword, semantic meaning, or both." in content
    assert not any("\u4e00" <= char <= "\u9fff" for char in content)
    assert "\x1b[" not in content
    assert "/home/" not in content


def test_generator_is_deterministic(tmp_path: Path):
    first = tmp_path / "first" / "cli-reference.md"
    second = tmp_path / "second" / "cli-reference.md"

    first_result = _run_generator(first, tmp_path / "first-home")
    second_result = _run_generator(second, tmp_path / "second-home")

    assert first_result.returncode == 0, first_result.stderr
    assert second_result.returncode == 0, second_result.stderr
    assert first.read_bytes() == second.read_bytes()
    assert (
        hashlib.sha256(first.read_bytes()).hexdigest()
        == hashlib.sha256(second.read_bytes()).hexdigest()
    )


def test_generator_config_safety(tmp_path: Path):
    real_config = Path.home() / ".zk_config.json"
    before_bytes = real_config.read_bytes() if real_config.exists() else None
    before_hash = hashlib.sha256(before_bytes).hexdigest() if before_bytes is not None else None
    before_data = json.loads(before_bytes) if before_bytes is not None else None
    output = tmp_path / "cli-reference.md"

    result = _run_generator(output, tmp_path)

    assert result.returncode == 0, result.stderr
    after_bytes = real_config.read_bytes() if real_config.exists() else None
    after_hash = hashlib.sha256(after_bytes).hexdigest() if after_bytes is not None else None
    after_data = json.loads(after_bytes) if after_bytes is not None else None
    assert after_hash == before_hash
    assert after_data == before_data
    assert not (REPO_ROOT / "zk_config.json").exists()
    assert not (REPO_ROOT / "config.json").exists()


@pytest.fixture(scope="module", autouse=True)
def generated_repository_reference():
    """Ensure committed-reference assertions use freshly generated output."""
    from scripts.generate_docs import generate_reference

    generate_reference(REFERENCE, DESCRIPTIONS)
    yield


@pytest.mark.parametrize(
    "command_path",
    sorted(EXPECTED_NESTED_PATHS),
)
def test_reference_contains_each_required_nested_command(command_path: str):
    content = REFERENCE.read_text(encoding="utf-8")

    assert f"## `{command_path}`" in content
